import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { ConvexClientWithClerkProvider } from "../providers/convex-client-with-clerk-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { Header } from "@/components/header";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${dmSans.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
          storageKey="theme"
        >
          <ConvexClientWithClerkProvider>
            <Header />
            {children}
          </ConvexClientWithClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
